# ==============================================
# Stellar TOML for CGX Token (CryptoGDEX)
# Network: Mainnet
# ==============================================

VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
SIGNING_KEY = "GAHCZ42GZTE644EXSBLBOBFMRGOO56SDLZ5XBKDWWSMZUQOHF3TGY7KW"

[DOCUMENTATION]
ORG_NAME = "CryptoG Group"
ORG_DBA = "CGX Token"
ORG_URL = "https://www.cryptogdex.io"
ORG_LOGO = "https://gateway.pinata.cloud/ipfs/bafkreiekzt4qpnprtiuts5j7gzn2xmgqp4ke2z5jib7agnzwbqm2vk7syq"
ORG_OFFICIAL_EMAIL = "info@cryptogdex.io"
ORG_OFFICIAL_TELEGRAM_CHANNEL = "https://t.me/cryptogdex"
ORG_OFFICIAL_MEDIUM_CHANNEL = "https://medium.com/@info_93306"
ORG_DESCRIPTION = """The CryptoG Group (the "Organization") is an anonymous, privately owned, non-profit organization of volunteer humanitarians and experts from various fields. Based in our anonymous community worldwide, we strive to break conventional financial ground by bridging liberated governance to give back power to the people through the issuance of the CGX token, and the upcoming CryptoG Bank - a fully decentralized, no-KYC banking layer built on Stellar's Soroban smart contracts."""
ORG_PHYSICAL_ADDRESS = "Decentralized"
ORG_KEYBASE = "cryptoggroup"

[[PRINCIPALS]]
name = "CryptoG Group"
email = "info@cryptogdex.io"

[[CURRENCIES]]
code = "CGX"
name = "CryptoGDEX"
issuer = "GAHCZ42GZTE644EXSBLBOBFMRGOO56SDLZ5XBKDWWSMZUQOHF3TGY7KW"
display_decimals = 7
is_asset_anchored = false
anchor_asset_type = "crypto"
status = "live"
desc = """The CryptoG Group (the "Organization") is an anonymous, privately owned, non-profit organization of volunteer humanitarians and experts from various fields. Based in our anonymous community worldwide, we strive to break conventional financial ground by bridging liberated governance to give back power to the people through the issuance of the CGX token, and the upcoming CryptoG Bank - a fully decentralized, no-KYC banking layer built on Stellar's Soroban smart contracts."""
image = "https://gateway.pinata.cloud/ipfs/bafkreiekzt4qpnprtiuts5j7gzn2xmgqp4ke2z5jib7agnzwbqm2vk7syq"
conditions = "The CGX token will serve as an essential mechanism for significantly enhancing liquidity across various pools, directly supporting our Bitcoin liquidation initiative. With a total supply of 1,100,000, it is strategically engineered to generate robust and continuous buying pressure, driving substantial growth in its market capitalization over time. This strategic approach not only broadens the appeal to a diverse array of token holders but also enhances market stability, fostering a resilient trading environment. In addition to its liquidity function, the token will empower users to engage in active trading and participate in staking opportunities that offer compelling rewards. Moreover, it will provide access to a comprehensive range of financial services within our innovative ecosystem. This includes a state-of-the-art decentralized exchange, grand launching in Q1 2026, enabling users to trade a diverse selection of digital assets securely and without the need for KYC verification. Furthermore, our advanced decentralized cryptocurrency banking platform, specifically designed to operate without interest, aims to meet the diverse financial needs of our community."
